# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d3b7b1ff2c03b49e16f473b869d92fc2713dd9239d189d4b0f3c32f6f5ee54c6a847847c755c89af1f830598e932fbfb422e2af3d60f5dc08aac3d4ea61d984

test:
  secret_key_base: e852649adfca11bf6137cc917a7c5e2dcc60c5cd9a4d4f6ddec7c660adf9d811c9efc289a83a2193c86779563276b373bf28ff5469a513df42d08fe40ea2d952

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
